### PR TITLE
Code clean up added new functions

### PR DESCRIPTION
**Pull request by montlikadani**
**Other:**
- Improved command registering.
- Added chat messages string list. - To list plugin commands.
- Removed with large first-name placeholders.
- Added README.md.

### CODE REVIEW

**Comment by kicjow** [comment]
Thanks for the pull request. Most of that code cleanup probably will be removed as my Intellij's code cleanup function will probably change most of those spaces back to empty lines.

**Comment by BBoyJD10** [comment]
Any news on this pull ?

**Comment by montlikadani** [comment]
yep

**Comment by montlikadani** [comment]
Other:
- Fix NullPointerExceptions
- Added 1.13 support

**Comment by montlikadani** [comment]
Other:
- Updated to 1.13.2 version.
- Fix version checking problems.

**Pull request closed without merging**
